### ISSUE TITLE
There is a problem with the translation result

### ISSUE THREAD

**Issue by yym68686** [Lin-jun-xiang/action-translate-readme#6]
This is my project: https:github.com/yym68686/ChatGPT-Telegram-Bot/blob/main/README.zh-TW.md

It can be seen that the font appears to be in Simplified Chinese.

**Comment by yym68686** [comment]
After making changes to the English README and pushing it, the original English version transformed into a simplified Chinese README, which appears somewhat perplexing. Although the traditional README is now displaying correctly

**Comment by Lin-jun-xiang** [comment]
@yym68686 
Thank feedback.
Could you try again? Because this problem often occurs in generate AI.

I used a test, and the result looked normal. => [Test](https://github.com/TommChen/TommChen)

However, I just made some modifications. When update README.md, I should avoid generating README.en.md and replact README.md

If there have any problem, just tag me!

**Comment by yym68686** [comment]
Thank you for your reply. I tried again and made some modifications to the English README. After pushing it, I noticed that there are issues with the Simplified Chinese README again. Here is the link:  https:github.com/yym68686/ChatGPT-Telegram-Bot/blob/main/README.zh-CN.md seems to have summarized my README. It appears that the instability is caused by the prompt. I hope it can be modified.

**Comment by Lin-jun-xiang** [comment]
@yym68686 
Thanks!
I've tried to improve the translate prompt.
This is the result base on your README: [Demo](https://github.com/Lin-jun-xiang/action-translate-readme/tree/prompt_adjust)

**Comment by yym68686** [comment]
Now it looks perfect, thank you!
